version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app/src:$PYTHONPATH 
    command: ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    command: ["yarn", "dev"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
